# Generated by Django 5.2.6 on 2025-10-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_hsn_code_remove_product_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=100, editable=False, max_digits=12),
            preserve_default=False,
        ),
    ]
