# Generated by Django 5.2.6 on 2025-10-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stock_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
