# Generated by Django 5.2.6 on 2025-10-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stock_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batch_number',
            field=models.CharField(max_length=100),
        ),
    ]
