# Generated by Django 5.2.6 on 2025-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_saleorder_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
