# Generated by Django 5.2.6 on 2025-10-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_remove_purchaseorderitem_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
