# Generated by Django 5.2.6 on 2025-10-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_purchaseorderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='batch_number',
            field=models.CharField(max_length=100),
        ),
    ]
