# Generated by Django 5.2.6 on 2025-10-19 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stock_batch_number'),
        ('purchase', '0009_alter_purchaseorder_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stock'),
        ),
    ]
