# Generated by Django 5.2.6 on 2025-10-19 12:53

from django.db import migrations


def populate_stock_field(apps, schema_editor):
    PurchaseOrderItem = apps.get_model('purchase', 'PurchaseOrderItem')
    Stock = apps.get_model('inventory', 'Stock')
    
    items = PurchaseOrderItem.objects.all()
    updated_count = 0
    
    for item in items:
        # Try to find matching stock entry based on product, batch_number, expiry_date, and purchase_price
        matching_stocks = Stock.objects.filter(
            product=item.product,
            batch_number=item.batch_number,
            expiry_date=item.expiry_date,
            purchase_price=item.purchase_price
        )
        
        if matching_stocks.exists():
            # Use the first matching stock entry
            item.stock = matching_stocks.first()
            item.save()
            updated_count += 1
            print(f"Updated item {item.id} with stock {item.stock.id}")
        else:
            print(f"No matching stock found for item {item.id}: {item.product.name}, batch {item.batch_number}")
    
    print(f"Updated {updated_count} out of {items.count()} purchase order items")


def reverse_populate_stock_field(apps, schema_editor):
    # This function would clear the stock field if needed
    PurchaseOrderItem = apps.get_model('purchase', 'PurchaseOrderItem')
    PurchaseOrderItem.objects.update(stock=None)


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_purchaseorderitem_stock'),
        ('inventory', '0006_alter_stock_total_price'),  # Ensure inventory Stock model exists
    ]

    operations = [
        migrations.RunPython(populate_stock_field, reverse_populate_stock_field),
    ]
