# Generated by Django 5.2.6 on 2025-10-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
